#!/usr/bin/env python3
"""Main held-out budget table and risk/payback figure; budget_arms.log only.

The table's RULE entries are median alpha, mean held-out recall (from the
rounded reported mean loss), and arithmetic mean of selected fixed-arm QPS.
They do not describe one newly measured service configuration. Payback uses
that same aggregate for a 500-query batch and excludes sample gathering.
"""
from pathlib import Path
import json
import budget_arms
import style
from style import plt, WIDE, DS_COLOR, DS_MARK, save


def main():
    cells = budget_arms.load()
    dst = Path(style.HERE).parent / 'tex' / 'tables'
    dst.mkdir(exist_ok=True)
    rows, stats = [], []
    def fmt(a, r, q):
        return r'\shortstack{$%g;\ %.4f$\\$%.1f$}' % (a, r, q / 1000)
    for (ds, np_), c in cells.items():
        fx = {a:(r,q) for a,r,q in c['fixed']}
        r = c['rule'][128]
        oa, ceiling, ore, oq = c['oracle']
        fa, fre, fq, fc = c['full']
        gain = r['qps'] / fx[100][1]
        repay = r['cal_ms'] / (500000 * (1 / fx[100][1] - 1 / r['qps']))
        stats.append(dict(dataset=ds,nprobe=np_,oracle_alpha=oa,
                          rule_alpha=r['alpha'],gain=gain,cal_ms=r['cal_ms'],
                          repay_batches=repay,mean_loss=r['mean'],p95_loss=r['p95'],
                          failures=round(64*r['over']),draws=64))
        name = ('Vogue' if ds=='vogue-768' else 'OpenAI')+r'\,/\,%d'%np_
        row=[name,fmt(8,*fx[8]),fmt(64,*fx[64]),
             fmt(r['alpha'],ceiling-r['mean'],r['qps']),
             fmt(fa,fre,fq),fmt(oa,ore,oq)]
        rows.append(' & '.join(row)+r' \\')
    (dst/'budget_current.tex').write_text(
        '% Generated by figures/current_budget.py\n'
        r'\footnotesize\setlength{\tabcolsep}{4pt}'+'\n'+
        r'\begin{tabular}{@{}lccccc@{}}\toprule'+'\n'+
        r'Dataset / probe & Fixed 8 & Fixed 64 & Rule & Full pool & Oracle \\ \midrule'+'\n'+
        '\n'.join(rows)+'\n'+r'\bottomrule\end{tabular}'+'\n')
    (dst/'budget_values.json').write_text(json.dumps(stats,indent=2)+'\n')
    # Each point carried its probe depth and calibration time as text.  That
    # was placed by hand for four points and does not survive twelve -- the
    # labels collide with each other and with the spines whatever the offset
    # rule.  Both quantities are columns of Table 2, so the panel keeps the
    # relationship it exists to show and drops the annotation.
    fig,(ax,bx)=plt.subplots(1,2,figsize=(WIDE,2.05))
    for (ds,np_),c in cells.items():
        ax.plot([32,64,128],[100*c['rule'][s]['over'] for s in [32,64,128]],
                color=DS_COLOR[ds], marker=DS_MARK[ds],
                ls='-' if np_==128 else '--',
                label=('%s / %d'%('Vogue' if ds=='vogue-768' else 'OpenAI',np_)))
    ax.set_xscale('log',base=2);ax.set_xticks([32,64,128]);ax.set_xticklabels(['32','64','128'])
    ax.set_xlabel('Calibration queries, S');ax.set_ylabel(r'Draws losing $>10^{-3}$ (%)')
    ax.set_ylim(-3,78)
    ax.legend(fontsize=6.2 if len(cells)>6 else 7, handlelength=1.1,
              ncol=2 if len(cells)>6 else 1, labelspacing=0.25, borderpad=0.25)
    ax.set_title('(a) Held-out quality risk',fontsize=8)
    for x in stats:
        ds=x['dataset'];np_=x['nprobe']
        bx.scatter(x['gain'],x['repay_batches'],color=DS_COLOR[ds],marker=DS_MARK[ds],
                   facecolors=DS_COLOR[ds] if np_==128 else 'none',s=26)
        # Offsets per point, not per probe depth: at (4,-13) the openai/512
        # label landed beside the vogue/128 marker and read as its label.
    gs=[x['gain'] for x in stats]; rs=[x['repay_batches'] for x in stats]
    sp=max(gs)-min(gs)+.01
    bx.set_xlim(min(gs)-0.10*sp, max(gs)+0.10*sp); bx.set_ylim(min(rs)*0.72, max(rs)*1.40)
    bx.set_yscale('log')
    # set_yticks fixes the major ticks, but the log locator keeps its own
    # minor ticks and the default formatter labels those too, so the axis
    # came out reading 2x10^1 / 16 / 8 / 6x10^0 / 4 / 3x10^0.
    bx.yaxis.set_minor_locator(style.matplotlib.ticker.NullLocator())
    tk=[v for v in (1,2,4,8,16,32,64) if min(rs)*0.7 <= v <= max(rs)*1.5]
    bx.set_yticks(tk)
    bx.yaxis.set_major_formatter(
        style.matplotlib.ticker.FixedFormatter([str(v) for v in tk]))
    bx.set_xlabel(r'Selected-arm QPS / fixed $\alpha=100$')
    bx.set_ylabel('Estimated batches to repay')
    bx.set_title('(b) Calibration economics, S=128',fontsize=8)
    fig.tight_layout(pad=.3,w_pad=1.3);save(fig,'fig_budget_current')
    print(json.dumps(stats,indent=2))

if __name__=='__main__':main()
