#!/usr/bin/env python3
"""Two LaTeX tables the body needs, generated so no number is typed by hand.

`frontier`  -- who is fastest at each matched recall, every baseline included.
              JHQ owns 4 of 26 comparable cells. A reviewer reading Figure 5
              works this out in a minute; stating it is the only way the paper
              keeps its credibility while claiming the region it does own.

`batch`     -- the matched-recall batch ratios. This replaces fig_batch, which
              was drawn from batch_sweep.log (a fixed-nprobe experiment) while
              the caption and the surrounding text described batch_matched.log.
              The figure was showing a different experiment from the one the
              text reported.

Both use log-linear interpolation of each system's curve at the target recall.
The cruder max(qps | recall >= target) disagrees -- 2.14 where interpolation
gives 2.23 on openai3-3072 at batch 32 -- because the two systems land at
slightly different recalls on a shared nprobe grid.
"""
import collections
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import style

NAME = {"cagra": "CAGRA-fp32", "cagra8": "CAGRA-int8", "ivfpq": "IVF-PQ"}
RECALLS = (0.90, 0.93, 0.95, 0.97, 0.98, 0.99)


MARGINS = collections.defaultdict(list)


def frontier_table():
    f, rq, bl = style.load_fronts(), style.load_rabitq(), style.load_baselines()
    lines, win, tot = [], 0, 0
    for ds in style.DATASETS:
        if ds not in f:
            continue
        cells = []
        for R in RECALLS:
            row = []
            q = style.interp(f[ds]["rule"], R)
            if q:
                row.append((q, "JHQ"))
            if ds in rq:
                q = style.interp(rq[ds], R)
                if q:
                    row.append((q, "RaBitQ"))
            for nm, pts in bl.get(ds, {}).items():
                if nm not in NAME:
                    continue
                q = style.interp(style.pareto(pts), R)
                if q:
                    row.append((q, NAME[nm]))
            if len(row) < 2:
                cells.append("--")
                continue
            row.sort(reverse=True)
            tot += 1
            best = row[0][1]
            jhq = dict((n, v) for v, n in row).get("JHQ")
            if best == "JHQ":
                win += 1
                cells.append(r"\textbf{JHQ}")
            else:
                # "CAGRA-int8 $2.7\times$" made the six-column table 30pt too
                # wide for the LNCS block; the caption expands the names.
                short = best.replace("CAGRA-", "").replace("RaBitQ", "RaBitQ")
                if jhq:
                    MARGINS[best].append(row[0][0] / jhq)
                cells.append("%s $%.1f\\times$" % (short, row[0][0] / jhq)
                             if jhq else short)
        lines.append("%s & %s \\\\" % (style.PRETTY[ds], " & ".join(cells)))
    return lines, win, tot


def batch_table():
    rows = collections.defaultdict(lambda: collections.defaultdict(list))
    for ln in open(style.datafile("batch_matched.log"), errors="ignore"):
        m = re.search(r"^\s*(JHQ|RaBitQ)\s+(\S+)\s+np=(\d+)\s+(?:a=[\d.]+\s+)?"
                      r"batch=(\d+)\s+recall=([\d.]+)\s+qps=(\d+)", ln)
        if m:
            rows[(m.group(2), int(m.group(4)))][m.group(1)].append(
                (float(m.group(5)), int(m.group(6))))
    out = []
    for b in (32, 128, 512, 1024):
        cells = []
        for ds in ("openai3-3072", "vogue-768"):
            cell = rows.get((ds, b), {})
            for tgt in (0.90, 0.95):
                v = [style.interp(sorted(cell.get(s, [])), tgt)
                     for s in ("JHQ", "RaBitQ")]
                cells.append("$%.2f$" % (v[0] / v[1]) if all(v) else "--")
        out.append("%d & %s \\\\" % (b, " & ".join(cells)))
    return out


def main():
    lines, win, tot = frontier_table()
    dst = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       os.pardir, "tex", "tables")
    os.makedirs(dst, exist_ok=True)
    with open(os.path.join(dst, "frontier.tex"), "w") as fh:
        fh.write("%% generated by figures/table_frontier.py -- do not edit\n")
        fh.write("\\footnotesize\n\\begin{tabular}{l%s}\n\\toprule\n"
                 % ("r" * len(RECALLS)))
        fh.write("& \\multicolumn{%d}{c}{fastest system at Recall@10}\\\\\n"
                 % len(RECALLS))
        fh.write("\\cmidrule(l){2-%d}\n" % (len(RECALLS) + 1))
        fh.write("dataset & %s \\\\\n\\midrule\n"
                 % " & ".join("$%.2f$" % r for r in RECALLS))
        fh.write("\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n")
    with open(os.path.join(dst, "batch.tex"), "w") as fh:
        fh.write("%% generated by figures/table_frontier.py -- do not edit\n")
        fh.write("\\begin{tabular}{rrrrr}\n\\toprule\n")
        fh.write("& \\multicolumn{2}{c}{openai3-3072} & "
                 "\\multicolumn{2}{c}{vogue-768}\\\\\n"
                 "\\cmidrule(lr){2-3}\\cmidrule(l){4-5}\n")
        fh.write("batch & $0.90$ & $0.95$ & $0.90$ & $0.95$ \\\\\n\\midrule\n")
        fh.write("\n".join(batch_table()) + "\n\\bottomrule\n\\end{tabular}\n")
    print("  wrote tex/tables/frontier.tex  (JHQ fastest in %d of %d cells)"
          % (win, tot))
    print("  ranges for the body, so they are not typed by hand:")
    for nm, v in sorted(MARGINS.items()):
        print("     %-11s leads in %2d cells, margin over JHQ %.1fx to %.1fx"
              % (nm, len(v), min(v), max(v)))
    print("  wrote tex/tables/batch.tex")


if __name__ == "__main__":
    main()
